name: Build Check and Execution

on:
  workflow_call:

jobs:
  build_check_and_execute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq -y

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies from package.json
        run: npm install

      - name: Check for Build Step in package.json
        id: build-check-step
        run: |
          build_command=$(jq -r '.scripts.build' package.json)
          # Replace 'ui5' with the correct path to ui5 command
          build_command="${build_command/ui5/$(npm bin)/ui5}"
          echo "BUILD_COMMAND=$build_command" >> $GITHUB_ENV

      - name: Run Build Step
        if: ${{ env.BUILD_COMMAND != '' }}
        run: |
          build_command="${BUILD_COMMAND}"
          eval "$build_command"
