name: Docker Build and Publish the SRB UI5 Quality Check App

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        working-directory: ./
        run: |
          docker build -t srb-ui5-quality-checks-app .

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: srb-ui5-quality-checks-app
          path: /var/lib/docker/image/overlay2/imagedb/content/sha256
