name: Build Check and Execution

on:
  workflow_call:

jobs:
  build_check_and_execute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq -y

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies globally from package.json
        run: npm install -g

      - name: Install the ui5 cli
        run: npm install --global @ui5/cli      

      - name: Check for Build Step in package.json
        id: build-check-step
        run: |
          build_command=$(jq -r '.scripts.build' package.json)
          echo "BUILD_COMMAND=$build_command" >> $GITHUB_ENV

      - name: Run Build Step
        if: ${{ env.BUILD_COMMAND != '' }}
        run: |
          build_command="${BUILD_COMMAND}"
          eval "$build_command"
