name: ESLint

on:
  push:
    branches:
      - main

  workflow_call:

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js v20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install ESLint and dependencies
        run: |
          npm install eslint eslint-plugin-react
          npm install --save-dev eslint-config-airbnb-base eslint-config-prettier eslint-plugin-import

      - name: Run ESLint
        run: npx eslint . #--config WorkflowsConfig/.eslintrc.yaml
