name: ESLint

on:
  workflow_call:

jobs:
  js-linter-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js v20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Download ESLint config file from QM repository
        run: |
          curl -o .eslintrc.js https://raw.githubusercontent.com/SRBConsultingTeam/SRB_UI5_QM/master/WorkflowConfig/.eslintrc.js

      - name: Install ESLint and dependencies
        run: |
          npm install eslint@8.7.0

      - name: Run ESLint
        run: npx eslint . --config .eslintrc.js

  xml-linter-job:
    runs-on: ubuntu-latest  
    steps:
      - name: Verify XML Action
        uses: Ahli/verify-xml-action@v2
        with:
          path: "/webapp"
          file-endings: ".xml"
      