name: "UI5 Quality Check App: SRB UI5 QM Workflow"
on:
  push:
    paths:
      - "UI5_Quality_Checks_App"
jobs:
  # Linter jobs for the quality checks app
  srb-reuse-linter:
    uses: SRBConsultingTeam/SRB_UI5_QM/.github/workflows/lint.yml@master
    with:
      ui5app_path: ./UI5_Quality_Checks_App

  # Builder jobs for the quality checks app
  srb-reuse-builder:
    uses: SRBConsultingTeam/SRB_UI5_QM/.github/workflows/build_check_and_execute.yml@master
    with:
      ui5app_path: ./UI5_Quality_Checks_App
