name: SRB UI5 QM Workflow Quality Checks App
on:
  push:

jobs:
  # Linter jobs for the quality checks app
  srb-reuse-linter-detail-component:
    uses: SRBConsultingTeam/SRB_UI5_QM/.github/workflows/lint.yml@master
    with:
      ui5app_path: ./UI5\ Quality\ Checks\ App/

  # Builder jobs for the quality checks app
  srb-reuse-builder-detail-component:
    uses: SRBConsultingTeam/SRB_UI5_QM/.github/workflows/build_check_and_execute.yml@master
    with:
      ui5app_path: ./UI5\ Quality\ Checks\ App/
